name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there, thank you for your first issue in our project.'
        pr-message: 'Hi there, welcome and thank you on your first pr in our project.'
